version: '3.8'

services:
  app:
    build: ./app
    container_name: node_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "8081:80"
      - "4433:443"
    volumes:
      - ./nginx:/etc/nginx
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - app_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: ["certbot"]
    command: ["certonly", "--webroot", "--webroot-path=/var/www/certbot", "--email", "elibubalteen@gmail.com", "--agree-tos", "--no-eff-email", "-d", "alhussainihealthcc.com", "--force-renewal"]
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
